### ISSUE TITLE
Annotation tiling previews crash on real slides: 'WSI' object has no attribute 'read_level'

### ISSUE THREAD

**Issue by clemsgrs** [clemsgrs/hs2p#148]
## Summary

Annotation-aware **tiling previews** crash on every real-slide run — `'WSI' object has no attribute 'read_level'` — so no tiling-preview JPEG is ever produced. The **mask preview renders correctly**; only the tiling previews are affected. Found via manual verification on the real `test-wsi.tif` fixture against `main` (`9dd2ea2`); the test suite is green because it never exercises the mask-overlay branch against a real backend.

Introduced by #147 (issue #144). Parent epic: #141.

## Root cause

`write_coordinate_preview` (`hs2p/wsi/visualization.py`) builds the backdrop mask as a **`WSI`**:

```
mask = WSI(mask_path, backend=backend)
```

and passes that `WSI` into `draw_grid_from_coordinates` → `read_aligned_mask`, which calls `mask_obj.read_level(mask_level)` (and `mask_obj.spacings`) in `hs2p/wsi/masks.py`. `read_level` is a **reader/backend** method — `WSI` doesn't define it (it exposes `read_region` / `read_region_at_spacing`). The mask-preview path gets this right by passing the reader: `overlay_mask_on_slide` uses `mask_obj=mask_object.reader`. The tiling-preview path passes the `WSI` itself.

It only fires when a **mask backdrop** is supplied — which the annotation tiling preview always does — so #144 drives a latent mismatch that the prior tissue path didn't.

## Reproduction

1. Author a multi-label mask (e.g. tumor=1, stroma=2) registered to a real WSI (the project's `scripts/generate_tissue_mask.py` `build_mask_pyramid` + `write_pyramidal_mask_tiff` helpers produce a backend-readable pyramidal TIFF).
2. Run the CLI with annotation sampling + `preview.save_tiling_preview: true`, in either `output_mode`.

Observed:
```
Generating previews (2 total)...
[tile_slides] FAILED test-wsi: 'WSI' object has no attribute 'read_level'
Preview generation: 0/2 complete, 2 failed
Run finished successfully.
```
`preview/tiling/` is empty; `preview/mask/<sample_id>.jpg` is written and correct (verified visually: per-label colors, α-blend, background not overlaid).

## Proposed fix

Pass the **reader** (not the `WSI`) into the grid renderer's mask-overlay path, mirroring `overlay_mask_on_slide` (`mask_obj=mask_object.reader`). i.e. in `write_coordinate_preview`/`draw_grid_from_coordinates`, hand `read_aligned_mask` a reader that implements `read_level`/`spacings`.

## Secondary finding (separate concern)

Preview failures are swallowed: the run prints `Run finished successfully` despite `Preview generation finished: 0/2 complete, 2 failed`. Consider surfacing preview failures more loudly (non-zero signal / summary line), so a broken preview path isn't mistaken for a successful one. Out of scope for the fix itself — noting it here.

## Acceptance criteria

- [ ] Annotation tiling previews render on a real (openslide/cucim-backed) slide in both PER_ANNOTATION and SINGLE_OUTPUT modes — a JPEG is written under `preview/tiling/` mirroring each coordinate artifact path.
- [ ] No `read_level` AttributeError; the mask backdrop is read via a reader, not a `WSI`.
- [ ] Mask-preview behavior is unchanged (still rendered, `mask_preview_path` repeated per row).
- [ ] A regression test exercises the tiling-preview mask-overlay branch against a backend whose `WSI` does **not** expose `read_level` (i.e. catches the WSI-vs-reader gap a fake backend can hide) — e.g. drive `tile_slides` on the real fixture slide with a multi-label mask, asserting the tiling-preview JPEG is actually produced.

## Blocked by

None - can start immediately.
